### ISSUE TITLE
Crash in 3.4.1

### ISSUE THREAD

**Issue by DimaVartanian** [keenlabs/KeenClient-iOS#114] opened 2015-08-03 18:21 UTC
I haven't repro'd this myself but already see a user in Crashlytics who just updated to the latest version of our app get this 7 times in a row when trying to start up the app. Hopefully this is enough info to see what's going on. I see this crash for the last few releases as well but it only happened once or twice total before. 

Crashed: io.keen.sqlite
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x0000000000000018
 raw
0
mobile	
keen_io_sqlite3.c line 65840
keen_io_sqlite3_reset
1
mobile	
KIOEventStore.m line 662
-[KIOEventStore resetSQLiteStatement:]
2
mobile	
KIOEventStore.m line 662
-[KIOEventStore resetSQLiteStatement:]
3
libdispatch.dylib	
_dispatch_client_callout + 16
4
libdispatch.dylib	
_dispatch_barrier_sync_f_invoke + 76
5
mobile	
KIOEventStore.m line 487
-[KIOEventStore getTotalEventCountWithProjectID:]
6
mobile	
KeenClient.m line 498
-[KeenClient addEvent:withKeenProperties:toEventCollection:error:]
7
mobile	
KeenClient.m line 462
-[KeenClient addEvent:toEventCollection:error:]
8
mobile	
DelectableAnalytics.m line 222
+[DelectableAnalytics blockingTrack:properties:]
9	libdispatch.dylib	
_dispatch_call_block_and_release + 24
14	libsystem_pthread.dylib	
start_wqthread + 4

**Comment by DimaVartanian** [comment] 2015-08-04 17:48
This issue is pretty bad. There are a few more users, up to 4 now, who are unable to use our app at all. I am trying to write to them to ask them to try reinstalling because I'm not sure what else to do.

**Comment by heitortsergent** [comment] 2015-08-05 23:11
@DimaVartanian really sorry about this issue. :(

If I may ask a few questions to try and solve this:

- Do you have any other information about what's happening that might help us pinpoint the issue?
- Which version of the SDK are you using?
- Is it the same issue for the 4 users?
- How are you initializing Keen and sending the events?

**Comment by DimaVartanian** [comment] 2015-08-06 15:52
Hi Heitor.
1. No other information because I have not had any communication with the users. I included the stacktrace above though. The only thing I know is that it happens immediately upon startup.
2. The version of the SDK is in the title (3.4.1). It appears as though the issue was occurring with the last version of your SDK as well but to a lesser extent.
3. According to the stacktrace it appears to be exactly the same.
4. I am initializing the SDK like this: [KeenClient sharedClientWithProjectID:@"50d24b86897a2c23cd000000" andWriteKey:@"key" andReadKey:@"key"];
I am sending the events like this:
[[KeenClient sharedClient] addEvent:properties toEventCollection:event error:nil];

**Comment by heitortsergent** [comment] 2015-08-07 17:28
@DimaVartanian thanks for the answers!

Looking at the stack trace, I believe the error might be lying with this part of the code:

`if (keen_io_sqlite3_bind_text(count_all_stmt, 1, [projectID UTF8String], -1, SQLITE_STATIC) != SQLITE_OK) {`

and more specifically:

`[projectID UTF8String]`

That object is probably being released before the method finishes its execution. I'm doing some tests to make sure that's the case, and hopefully have a fix out soon.

**Comment by heitortsergent** [comment] 2015-08-10 18:02
@DimaVartanian did you manage to find a way to reproduce the issue?

I really couldn't find a way to reproduce it, but looking at the documentation for the `UTF8String` inside the `NSString` class, I made a small change to the code that should make sure the UTF8String pointer sticks around for at least until the method finishes its execution. I opened a PR with the changes if you want to take a look. :dancer:

**Comment by DimaVartanian** [comment] 2015-08-10 21:35
I'm not sure this is the issue. If that is the case it would be a race condition so I wrapped the call in a `dispatch_after` delaying for a few seconds and could not repro the crash. In addition, most of the calls using `[projectID UTF8String]` use a `dispatch_sync` so the method should not go out of scope until the block returns. There are 2 places that actually does use a `dispatch_async` (`purgePendingEventsWithProjectID` and `resetPendingEventsWithProjectID`, is that intentional?) but neither one of those seem to be directly related to the crash anyway which seems to just be coming from `getTotalEventCountWithProjectID`.

**Comment by heitortsergent** [comment] 2015-08-10 22:38
@DimaVartanian I'm not sure this is the issue as well, but I'm thinking it's not a race condition but a low memory issue. Can you see if the crash happened when devices had low memory available?

The UTF8String property reference says:

```
This C string is a pointer to a structure inside the string object, which may have a lifetime shorter than the string object and will certainly not have a longer lifetime. Therefore, you should copy the C string if it needs to be stored outside of the memory context in which you use this property.
```

So what I think it's happening is that the dispatch_sync block is getting rid of the UTF8String reference before it's finished executing, since it's only being passed to the SQLite statement and not being stored anywhere else.

**Comment by heitortsergent** [comment] 2015-08-11 20:03
I'm gonna keep the issue open until we're sure it's fixed.

**Comment by DimaVartanian** [comment] 2015-08-11 21:10
I checked the reports and most users seemed to have at least 200MB+ of free memory, so no trend there unfortunately.

**Comment by heitortsergent** [comment] 2015-08-11 22:30
@DimaVartanian thanks for checking that information. :)

I'm really sorry that this is happening. I just merged the release bits for 3.4.3, so it should be available on CocoaPods and the .zip in a bit. Which one are you using?

I know it's unlikely that it fixed the issue from what we've been discussing, but could you update your app with it and see if the crashes stop?

I'm gonna keep looking into other reasons this might be happening and keep updating this thread.

**Comment by komamitsu** [comment] 2016-01-22 06:31
@DimaVartanian I ran into a similar crash when I enabled "Data Protection" and called a sqlite3 API in `applicationDidEnterBackground`. How about trying to reproducing this issue with "Data Protection"?

**Comment by heitortsergent** [comment] 2016-01-22 16:18
@komamitsu thanks, that's great to know! I'll try this as soon as I finish #140 :boom:

**Comment by heitortsergent** [comment] 2016-03-01 22:12
@komamitsu I still couldn't reproduce the issue with "Data Protection" enabled, but thanks for the tip!

@DimaVartanian are you still seeing this error, even with the newest version of the SDK?

**Comment by DimaVartanian** [comment] 2016-03-01 22:29
We actually stopped using Keen on our clients a few months ago. We instead use Segment for all client analytics and funnel through there to send to Keen and other services on our backend. So in a sense, the problem did stop happening, but not for the reason you were hoping. Sorry I can't be of more help.

**Comment by heitortsergent** [comment] 2016-03-01 22:38
@DimaVartanian thanks for the quick response! I'm glad you found a workaround :+1: , and I'm really sorry about the issue in the first place.

I'm going to close this for now since we haven't had any other reports of the same error, and we can't currently reproduce it.

**Closed by heitortsergent** 2016-03-01 22:38 UTC

**Comment by komamitsu** [comment] 2016-03-04 11:28
@heitortsergent 

I can reproduce this crash like this:

1) Create and set up a new project that uses KeenClient-iOS

2) Modify `AppDelegate.m`
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [KeenClient enableLogging];
    [KeenClient sharedClientWithProjectID:@"your_project_id" andWriteKey:@"your_write_key" andReadKey:@"your_read_key"];
    
    NSDictionary *event = [NSDictionary dictionaryWithObjectsAndKeys:@"first view", @"view_name", @"going to", @"action", nil];
    [[KeenClient sharedClient] addEvent:event toEventCollection:@"tab_views" error:nil];
    return YES;
}

- (void)applicationWillResignActive:(UIApplication *)application {
    [NSThread sleepForTimeInterval:10];
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
    UIBackgroundTaskIdentifier taskId = [application beginBackgroundTaskWithExpirationHandler:^(void) {
        NSLog(@"Background task is being expired.");
    }];
    
    [[KeenClient sharedClient] uploadWithFinishedBlock:^(void) {
        [application endBackgroundTask:taskId];
    }];
}
```
The key point is `[NSThread sleepForTimeInterval:10]` which simulates some other tasks that take long time before calling `uploadWithFinishedBlock`.

3) Enable "Data Protection" feature

4) Launch the project on real device and lock the device

5) After the application says `Failed to get count of pending rows: disk I/O error`, it crashes
